### ISSUE TITLE
Piping in JSON not working

### ISSUE THREAD

**Issue by CAmoruso** [rezanid/PSDataverse#16]
I am having issues running even the most basic commands when piping JSON into the Send-DataverseOperation function. The commands work if I provide the operation after the call to Send-DataverseOperation like this: Send-DataverseOperation '{"Uri":"WhoAmI"}'  but when piping them in following the example in the read me file ('{"Uri":"WhoAmI"}' | Send-DataverseOperation) I get the following error: Send-DataverseOperation: No operation has been given. Please provide an operation using either of -InputOperation or -InputJson or -InputObject arguments.

Piping in non JSON commands does seem to work, for example the following works just fine: @{Uri="WhoAmI"} | Send-DataverseOperation

**Comment by rezanid** [comment]
Thanks for reporting this. I found the culprit. There'll be a new update today.

**Comment by rezanid** [comment]
You can download the version 0.0.4 from PowerShell Gallery or here.
