### ISSUE TITLE
-Batchsize does not handle in-line If/else statements

### ISSUE THREAD

**Issue by Tomsecor** [rezanid/PSDataverse#27]
When writing if/else statements inside a for each record statement, it seems that the -batchsize command is unable to read that logic. Running the send-Dataverseoperation 1 record at a time runs with no issue. When using an if directly after the for each and then and else, repeating all columns, -batchsize works with that.

**Comment by rezanid** [comment]
@Tomsecor thanks for reporting this issue, could you also write a sample script here in the issue so I can reproduce it easily?

**Comment by Tomsecor** [comment]
Of course 
` 
Connect-Dataverse "authority =***
@{Uri="WhoAmI"} | Send-DataverseOperation | out-null

Import-Csv "AttachmentWithGuids.csv" | ForEach-Object {@{Uri="***"; Method = "POST"; Value = @{
"***_attachmentid"=$_."GUID"; 
"***_Pole@odata.bind"="/***_assets("+$_."Pole_GUID"+")";
"***_Height@odata.bind"=if($_."HeightGuid"-ne '')
{
"/***_poleheights("+$_."HeightGuid"+")"; 
}
else{}
"***_billable"="TRUE"; 
}}
} | Send-DataverseOperation -MaxDop 20 -BatchSize 500` 

The height field could potentially be null, when using batch size with this type of if statement, it fails
However batchsize does work if the entire import-CSV statement is repeated with an if at the beginning.

**Comment by rezanid** [comment]
May I also ask what error are you getting when you do this?

**Comment by Tomsecor** [comment]
It does not throw any errors in the cmd terminal. Just fast changesets, and no records are imported into the dataverse

**Comment by rezanid** [comment]
TBH, I didn't really check to see if anything got updated. I will do another test and monitor more closely.

**Comment by Tomsecor** [comment]
Were you able to replicate it?

**Comment by rezanid** [comment]
I did some more tests. I think I know what's happening in your case. You are getting some kind of operations errors inside your batches. The `Send-DataverseOperation` cmdlet returns `BatchResponse` objects that you can analyze to see all the details. Each `BactResponse` has a few properties that can help you get to the bottom of everything.
* `IsSuccessful` - will tell you if the batch has failed or not.
* `Operations` - is basically the list of all **operation responses** in the batch. This is where you need to look to find the root cause.

I usually have a method called Store-BatchResponse which I pipe at the end to store the what's interesting in a SQL table or CSV, etc. Then the sample would look like the following:
```
1..10 | ForEach-Object { @{Uri="accounts"; Method="PATCH"; Value=@{
  name=if($_ % 2 -eq 0) {
    "Even " + $_
  } else {
    "Odd " + $_}}}} | Send-DataverseOperation -BatchSize 2 -MaxDop 5 -InformationAction Continue |
  Store-BatchResponses
```

To improve performance I do not throw for every little error reported by WebAPI. I simply treat as business as usual and store it in BatchResponses. For really serious errors I throw in the cmdlet, and even if you want to catch then, you can add `-ErrorVariable ErrOperations` which will give you a list of `BatchException` objects which has similar properties.

I should write a more advanced script in the docs soon. That would make it easier for more advanced users like you ;)

**Comment by Tomsecor** [comment]
I am having some trouble reading the batch response, I am able to output it to the console or write it to a CSV but when writing to a csv I just get -changeset (guid)
When outputting it to the PS console I get something like `ontent-Type: multipart/mixed;boundary=changeset_0e22c762-b4df-4633-8435-2417cb2011a8

--changeset_0e22c762-b4df-4633-8435-2417cb2011a8
Content-Type:application/http
Content-Transfer-Encoding:binary
Content-ID:1

POST evergrn_permits HTTP/1.1
Content-Type:application/json;type=entry

"{\u0022evergrn_description\u0022:\u0022(Charter) 1440 W Williams Ave TRANSMISSION\u0022,\u0022evergrn_permitnumber\u0022:\u0022TK1581\u0022,\u0022modifiedon\u0022:null,\u0022evergrn_permitid\u0022:\u0022FFD790FD-7154-4DC9-AEE3-F3149A507F64\u0022,\u0022evergrn_requesteddate\u0022:\u00225/1/2017 0:00\u0022,\u0022evergrn_Contract@odata.bind\u0022:\u0022/evergrn_contracts(2469ad84-96ed-46d6-9d86-681e045c670c)\u0022,\u0022evergrn_Type@odata.bind\u0022:\u0022/evergrn_permittypes(71191FCC-5EED-42DC-96E7-D23D240BDCD0)\u0022,\u0022overriddencreatedon\u0022:\u00225/3/2017 18:37\u0022,\u0022evergrn_numberofpoles\u0022:null,\u0022evergrn_effectivedate\u0022:\u00225/3/2017 0:00\u0022,\u0022statuscode\u0022:\u0022157170001\u0022}"
--changeset_0e22c762-b4df-4633-8435-2417cb2011a8
Content-Type:application/http
Content-Transfer-Encoding:binary
Content-ID:2`


This is what I am doing `$batchResponse = (Import-Csv "Permit.csv" | ForEach-Object { @{Uri="evergrn_permits"; Method = "POST"; Value = @{
    "evergrn_permitid"=$_."GUID"; 
    "overriddencreatedon"=$_."createdon";
    "modifiedon"=$_."UpdatedOn";
    "statuscode"=$_."Status"; 
    "evergrn_permitnumber"=$_."permitId";
    "evergrn_effectivedate"=$_."EffectiveDate";
    "evergrn_description"=$_."description";
    "evergrn_requesteddate"=if($_."RequestedOn"-ne '')
    {
    $_."RequestedOn"; 
    }
    else{}
    "evergrn_Type@odata.bind"="/evergrn_permittypes("+$_."Type"+")";
    "evergrn_Contract@odata.bind"="/evergrn_contracts("+$_."Contract"+")";
    "evergrn_numberofpoles"=if($_."LengthOfConduit" -ne '') {
        $_."LengthOfConduit"
    }
    else{}

    }}} | Send-DataverseOperation -BatchSize 10 -MaxDop 5 -ErrorVariable ErrOperations)
    write-host $batchResponse`

Would you mind telling me where I am going wrong?

**Comment by Tomsecor** [comment]
> I am having some trouble reading the batch response, I am able to output it to the console or write it to a CSV but when writing to a csv I just get -changeset (guid) When outputting it to the PS console I get something like
> 
> ```
> 
> --changeset_0e22c762-b4df-4633-8435-2417cb2011a8
> Content-Type:application/http
> Content-Transfer-Encoding:binary
> Content-ID:1
> 
> POST evergrn_permits HTTP/1.1
> Content-Type:application/json;type=entry
> 
> "{\u0022evergrn_description\u0022:\u0022(Charter) 1440 W Williams Ave TRANSMISSION\u0022,\u0022evergrn_permitnumber\u0022:\u0022TK1581\u0022,\u0022modifiedon\u0022:null,\u0022evergrn_permitid\u0022:\u0022FFD790FD-7154-4DC9-AEE3-F3149A507F64\u0022,\u0022evergrn_requesteddate\u0022:\u00225/1/2017 0:00\u0022,\u0022evergrn_Contract@odata.bind\u0022:\u0022/evergrn_contracts(2469ad84-96ed-46d6-9d86-681e045c670c)\u0022,\u0022evergrn_Type@odata.bind\u0022:\u0022/evergrn_permittypes(71191FCC-5EED-42DC-96E7-D23D240BDCD0)\u0022,\u0022overriddencreatedon\u0022:\u00225/3/2017 18:37\u0022,\u0022evergrn_numberofpoles\u0022:null,\u0022evergrn_effectivedate\u0022:\u00225/3/2017 0:00\u0022,\u0022statuscode\u0022:\u0022157170001\u0022}"
> --changeset_0e22c762-b4df-4633-8435-2417cb2011a8
> Content-Type:application/http
> Content-Transfer-Encoding:binary
> Content-ID:2```
> 
> 
> 
> 
> This is what I am doing 
> 
>  ```$batchResponse = (Import-Csv "Permit.csv" | ForEach-Object { @{Uri="evergrn_permits"; Method = "POST"; Value = @{
>     "evergrn_permitid"=$_."GUID"; 
>     "overriddencreatedon"=$_."createdon";
>     "modifiedon"=$_."UpdatedOn";
>     "statuscode"=$_."Status"; 
>     "evergrn_permitnumber"=$_."permitId";
>     "evergrn_effectivedate"=$_."EffectiveDate";
>     "evergrn_description"=$_."description";
>     "evergrn_requesteddate"=if($_."RequestedOn"-ne '')
>     {
>     $_."RequestedOn"; 
>     }
>     else{}
>     "evergrn_Type@odata.bind"="/evergrn_permittypes("+$_."Type"+")";
>     "evergrn_Contract@odata.bind"="/evergrn_contracts("+$_."Contract"+")";
>     "evergrn_numberofpoles"=if($_."LengthOfConduit" -ne '') {
>         $_."LengthOfConduit"
>     }
>     else{}
>     }}} | Send-DataverseOperation -BatchSize 10 -MaxDop 5 -ErrorVariable ErrOperations)
>     write-host $batchResponse
> ```
> 
> Would you mind telling me where I am going wrong?

I was able to figure it out and was able to get this response from a batch 
 "Error identified in Payload provided by the user for Entity :'evergrn_assets', For more information on this error please follow this help link https://go.microsoft.com/fwlink/?linkid=2195293  ---->  InnerException : Microsoft.OData.ODataException: The 'odata.bind' instance or property annotation has a null value. In OData, the 'odata.bind' instance or property annotation must have a non-null string value.\r\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadAndValidateAnnotationStringValue(String annotationName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadAndValidateAnnotationStringValueAsUri(String annotationName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadEntryPropertyAnnotationValue(String propertyAnnotationName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadODataOrCustomInstanceAnnotationValue(String annotatedPropertyName, String annotationName, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ParseProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, String& parsedPropertyName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadNextNestedInfo()\r\n   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtNestedResourceInfoEndImplementation()\r\n   at Microsoft.OData.ODataReaderCore.ReadImplementation()\r\n   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)\r\n   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)\r\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger).",
            
If I were to do the records in this batch 1 by 1 it would work

**Comment by rezanid** [comment]
One thing you can try is instead of piping the result at the end to Send-DataverseOperation, pipe it to a cmdlet that writes to a file. Then you can open the file and go through the operations and try to find whats wrong with your operation. When PSDaraverse puts operations in batches, it doesn't manipulate the data in any way. If there are operations that can fail, they would fail the whole batch.

**Comment by Tomsecor** [comment]
If it cant manipulate data in any way in a batch, then the in-line if/else statement would fail, which would give that error, as the lookup requires a value or no value, it cannot be  "null" if the batch method cant see that lookup values can be empty, then it would never work with per line (in-line) if/else statements. I think it works when the if/else statement is outside the batch because it checks that first before making the batch

**Comment by rezanid** [comment]
The problem you are facing is not related to the `Send-DataverseOperation`, since it just sends what it receives from the pipeline. I have here another example of a pipeline which a foreach that changes data before piping it into `Send-DataverseOperation`.

```powershell

        $businessUnit = ConvertTo-Json ([pscustomobject]@{Uri="businessunits?`$filter= name eq 'SSO'&`$select=businessunitid";Method="GET"}) | Send-DataverseOperation | Select-Object -ExpandProperty Content | ConvertFrom-Json | Select-Object -ExpandProperty value
        $ownerTeam = ConvertTo-Json ([pscustomobject]@{Uri="teams?`$filter= name eq 'SSO managers'&`$select=teamid";Method="GET"}) | Send-DataverseOperation | Select-Object -ExpandProperty Content | ConvertFrom-Json | Select-Object -ExpandProperty value
        
        $existingUsers = ConvertTo-Json ([pscustomobject]@{Uri="systemusers?`$select=firstname,lastname,gen_s_salesforceid";Method="GET"}) | Send-DataverseOperation | Select-Object -ExpandProperty Content | ConvertFrom-Json | Select-Object -ExpandProperty value

        Measure-Command {
            Invoke-DbaQuery -SqlInstance $SqlInstance -Database $SqlDBName -Query "SELECT [Id], [FirstName], [LastName], [Operation] FROM vUserOperation" | 
            ForEach-Object { 
                $foundUser = [Array]::Find($existingUsers, [Predicate[object]]{ $args[0].firstname -eq $_.FirstName -And $args[0].lastname -eq $_.LastName })
                if ($foundUser) {
                    ConvertTo-Json ([pscustomobject]@{ContentId=$_.Id;Uri="systemusers($($foundUser.systemuserid))";Method="PATCH";Value=@{gen_s_salesforceid=$_.Id}}) | Send-DataverseOperation 
                } else {
                    $operation = $_.Operation.ToString().Replace("{{businessunitid}}", $businessUnit.businessunitid).Replace("{{teamid}}", $ownerTeam.teamid)
                    Send-DataverseOperation $operation -InformationAction Continue -Debug -ErrorVariable ErrOperation
                }
            } | 
            Store-SuccessHistory
            # Write errors in history table
            if ($ErrOperation) { $ErrOperation | Store-FailureHistory }
        } | Write-Measurement
```
