### ISSUE TITLE
Syntax Error in Connect-Dataverse Example #3

### ISSUE THREAD

**Issue by tsileo-wdi** [rezanid/PSDataverse#32]
The third Connect-Dataverse example should have "clientid" instead of "client_id" (current example leads to `Connect-Dataverse: The given key 'clientid' was not present in the dictionary.`).

In addition it is also missing the resource key (which is present in the other examples).

I the example should be like this:
`Connect-Dataverse "authority=https://login.microsoftonline.com/<your-tenant-id>/oauth2/authorize;clientid=1950a258-227b-4e31-a9cf-717495945fc2;device=true;resource=https://<your-environment-name>.crm4.dynamics.com/" -InformationAction Continue`

**Comment by rezanid** [comment]
You are right! thanks for reporting this. I will correct.

**Comment by rezanid** [comment]
done
