### ISSUE TITLE
Devicelogin flow can't detect device compliance

### ISSUE THREAD

**Issue by rvdwegen** [rezanid/PSDataverse#42]
Hi,

In my organization we require a device to be managed and compliant through Conditional Access before we allow authentication, the devicelogin flow can't detect if that's the case. 
Probably because its using Webview2 which can't read that information for some reason.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1940
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1878

![1111111111111111111Screenshot 2024-02-02 112834](https://github.com/rezanid/PSDataverse/assets/20259120/972d6ec1-0f01-4a99-9ec4-380cdb387f2a)

**Comment by rezanid** [comment]
Thanks for reporting this. I will investigate a bit soon.

**Comment by rezanid** [comment]
Coming back to you on the issue. I believe this is an issue in the conditional access policy that is blocking you. Perhaps the client id that you are using which is the identifier of Azure PowerShell is not allowed. What you can do is to use the client id of an Application Registration that is approved by your administrator.

The PSDataverse module is not using WebView or any other UI library. That's the whole point of device flow in fact ;) to be able to authenticate from devices that do not necessarily have any display.
